// Code generated by protoc-gen-go.
// source: Game.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	Game.proto

It has these top-level messages:
	Game
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Game struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}

type Game_PlayerInfo struct {
	Level             *int32  `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp               *int32  `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Hp                *int32  `protobuf:"varint,3,opt,name=hp" json:"hp,omitempty"`
	Energy            *int32  `protobuf:"varint,4,opt,name=energy" json:"energy,omitempty"`
	EnergyMax         *int32  `protobuf:"varint,5,opt,name=energy_max" json:"energy_max,omitempty"`
	Vip               *int32  `protobuf:"varint,6,opt,name=vip" json:"vip,omitempty"`
	Gold              *int32  `protobuf:"varint,7,opt,name=gold" json:"gold,omitempty"`
	Diamond           *int32  `protobuf:"varint,8,opt,name=diamond" json:"diamond,omitempty"`
	Power             *int32  `protobuf:"varint,9,opt,name=power" json:"power,omitempty"`
	Nick              *string `protobuf:"bytes,10,opt,name=nick" json:"nick,omitempty"`
	Signature         *string `protobuf:"bytes,11,opt,name=signature" json:"signature,omitempty"`
	Option            []bool  `protobuf:"varint,12,rep,name=option" json:"option,omitempty"`
	SignDays          *int32  `protobuf:"varint,13,opt,name=sign_days" json:"sign_days,omitempty"`
	AchievementPoints *int32  `protobuf:"varint,14,opt,name=achievement_points" json:"achievement_points,omitempty"`
	TaskPoints        *int32  `protobuf:"varint,15,opt,name=task_points" json:"task_points,omitempty"`
	RoleId            *int64  `protobuf:"varint,16,opt,name=role_id" json:"role_id,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Game_PlayerInfo) Reset()         { *m = Game_PlayerInfo{} }
func (m *Game_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*Game_PlayerInfo) ProtoMessage()    {}

func (m *Game_PlayerInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_PlayerInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_PlayerInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Game_PlayerInfo) GetEnergy() int32 {
	if m != nil && m.Energy != nil {
		return *m.Energy
	}
	return 0
}

func (m *Game_PlayerInfo) GetEnergyMax() int32 {
	if m != nil && m.EnergyMax != nil {
		return *m.EnergyMax
	}
	return 0
}

func (m *Game_PlayerInfo) GetVip() int32 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *Game_PlayerInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_PlayerInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *Game_PlayerInfo) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Game_PlayerInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Game_PlayerInfo) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *Game_PlayerInfo) GetOption() []bool {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *Game_PlayerInfo) GetSignDays() int32 {
	if m != nil && m.SignDays != nil {
		return *m.SignDays
	}
	return 0
}

func (m *Game_PlayerInfo) GetAchievementPoints() int32 {
	if m != nil && m.AchievementPoints != nil {
		return *m.AchievementPoints
	}
	return 0
}

func (m *Game_PlayerInfo) GetTaskPoints() int32 {
	if m != nil && m.TaskPoints != nil {
		return *m.TaskPoints
	}
	return 0
}

func (m *Game_PlayerInfo) GetRoleId() int64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

type Game_HeroAttr struct {
	Id               *int32            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid              *int32            `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Type             *int32            `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Sex              *int32            `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	Pos              *int32            `protobuf:"varint,5,opt,name=pos" json:"pos,omitempty"`
	Level            *int32            `protobuf:"varint,6,opt,name=level" json:"level,omitempty"`
	Exp              *int32            `protobuf:"varint,7,opt,name=exp" json:"exp,omitempty"`
	Hp               *int32            `protobuf:"varint,8,opt,name=hp" json:"hp,omitempty"`
	StarLevel        *int32            `protobuf:"varint,10,opt,name=star_level" json:"star_level,omitempty"`
	StepLevel        *int32            `protobuf:"varint,11,opt,name=step_level" json:"step_level,omitempty"`
	Speed            *int32            `protobuf:"varint,12,opt,name=speed" json:"speed,omitempty"`
	Zodiac           *int32            `protobuf:"varint,13,opt,name=zodiac" json:"zodiac,omitempty"`
	Feature          *string           `protobuf:"bytes,14,opt,name=feature" json:"feature,omitempty"`
	Name             *string           `protobuf:"bytes,15,opt,name=name" json:"name,omitempty"`
	PhysicalAttack   *int32            `protobuf:"varint,16,opt,name=physical_attack" json:"physical_attack,omitempty"`
	MagicAttack      *int32            `protobuf:"varint,17,opt,name=magic_attack" json:"magic_attack,omitempty"`
	PhysicalDefense  *int32            `protobuf:"varint,18,opt,name=physical_defense" json:"physical_defense,omitempty"`
	MagicDefense     *int32            `protobuf:"varint,19,opt,name=magic_defense" json:"magic_defense,omitempty"`
	Skill            []int32           `protobuf:"varint,20,rep,name=skill" json:"skill,omitempty"`
	Attribute        []*Game_Attribute `protobuf:"bytes,21,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_HeroAttr) Reset()         { *m = Game_HeroAttr{} }
func (m *Game_HeroAttr) String() string { return proto.CompactTextString(m) }
func (*Game_HeroAttr) ProtoMessage()    {}

func (m *Game_HeroAttr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_HeroAttr) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Game_HeroAttr) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_HeroAttr) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *Game_HeroAttr) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *Game_HeroAttr) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_HeroAttr) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_HeroAttr) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Game_HeroAttr) GetStarLevel() int32 {
	if m != nil && m.StarLevel != nil {
		return *m.StarLevel
	}
	return 0
}

func (m *Game_HeroAttr) GetStepLevel() int32 {
	if m != nil && m.StepLevel != nil {
		return *m.StepLevel
	}
	return 0
}

func (m *Game_HeroAttr) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Game_HeroAttr) GetZodiac() int32 {
	if m != nil && m.Zodiac != nil {
		return *m.Zodiac
	}
	return 0
}

func (m *Game_HeroAttr) GetFeature() string {
	if m != nil && m.Feature != nil {
		return *m.Feature
	}
	return ""
}

func (m *Game_HeroAttr) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Game_HeroAttr) GetPhysicalAttack() int32 {
	if m != nil && m.PhysicalAttack != nil {
		return *m.PhysicalAttack
	}
	return 0
}

func (m *Game_HeroAttr) GetMagicAttack() int32 {
	if m != nil && m.MagicAttack != nil {
		return *m.MagicAttack
	}
	return 0
}

func (m *Game_HeroAttr) GetPhysicalDefense() int32 {
	if m != nil && m.PhysicalDefense != nil {
		return *m.PhysicalDefense
	}
	return 0
}

func (m *Game_HeroAttr) GetMagicDefense() int32 {
	if m != nil && m.MagicDefense != nil {
		return *m.MagicDefense
	}
	return 0
}

func (m *Game_HeroAttr) GetSkill() []int32 {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *Game_HeroAttr) GetAttribute() []*Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Game_Attribute struct {
	Key              *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Value            *float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Game_Attribute) Reset()         { *m = Game_Attribute{} }
func (m *Game_Attribute) String() string { return proto.CompactTextString(m) }
func (*Game_Attribute) ProtoMessage()    {}

func (m *Game_Attribute) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Game_Attribute) GetValue() float32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Game_HeroStruct struct {
	HeroInfo         *Game_HeroAttr    `protobuf:"bytes,1,opt,name=hero_info" json:"hero_info,omitempty"`
	Attribute        []*Game_Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_HeroStruct) Reset()         { *m = Game_HeroStruct{} }
func (m *Game_HeroStruct) String() string { return proto.CompactTextString(m) }
func (*Game_HeroStruct) ProtoMessage()    {}

func (m *Game_HeroStruct) GetHeroInfo() *Game_HeroAttr {
	if m != nil {
		return m.HeroInfo
	}
	return nil
}

func (m *Game_HeroStruct) GetAttribute() []*Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Game_PropStruct struct {
	PropId           *int32 `protobuf:"varint,1,opt,name=prop_id" json:"prop_id,omitempty"`
	PropUid          *int32 `protobuf:"varint,2,opt,name=prop_uid" json:"prop_uid,omitempty"`
	PropCount        *int32 `protobuf:"varint,3,opt,name=prop_count" json:"prop_count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_PropStruct) Reset()         { *m = Game_PropStruct{} }
func (m *Game_PropStruct) String() string { return proto.CompactTextString(m) }
func (*Game_PropStruct) ProtoMessage()    {}

func (m *Game_PropStruct) GetPropId() int32 {
	if m != nil && m.PropId != nil {
		return *m.PropId
	}
	return 0
}

func (m *Game_PropStruct) GetPropUid() int32 {
	if m != nil && m.PropUid != nil {
		return *m.PropUid
	}
	return 0
}

func (m *Game_PropStruct) GetPropCount() int32 {
	if m != nil && m.PropCount != nil {
		return *m.PropCount
	}
	return 0
}

type Game_FormationStruct struct {
	HeroId           *int32 `protobuf:"varint,1,opt,name=hero_id" json:"hero_id,omitempty"`
	HeroUid          *int32 `protobuf:"varint,2,opt,name=hero_uid" json:"hero_uid,omitempty"`
	Pos              *int32 `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_FormationStruct) Reset()         { *m = Game_FormationStruct{} }
func (m *Game_FormationStruct) String() string { return proto.CompactTextString(m) }
func (*Game_FormationStruct) ProtoMessage()    {}

func (m *Game_FormationStruct) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *Game_FormationStruct) GetHeroUid() int32 {
	if m != nil && m.HeroUid != nil {
		return *m.HeroUid
	}
	return 0
}

func (m *Game_FormationStruct) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type Game_EquipInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid              *int32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	EquipLevel       *int32 `protobuf:"varint,3,opt,name=equip_level" json:"equip_level,omitempty"`
	StrengthenCount  *int32 `protobuf:"varint,4,opt,name=strengthen_count" json:"strengthen_count,omitempty"`
	RefineCount      *int32 `protobuf:"varint,5,opt,name=refine_count" json:"refine_count,omitempty"`
	Pos              *int32 `protobuf:"varint,6,opt,name=pos" json:"pos,omitempty"`
	Quality          *int32 `protobuf:"varint,7,opt,name=quality" json:"quality,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_EquipInfo) Reset()         { *m = Game_EquipInfo{} }
func (m *Game_EquipInfo) String() string { return proto.CompactTextString(m) }
func (*Game_EquipInfo) ProtoMessage()    {}

func (m *Game_EquipInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_EquipInfo) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Game_EquipInfo) GetEquipLevel() int32 {
	if m != nil && m.EquipLevel != nil {
		return *m.EquipLevel
	}
	return 0
}

func (m *Game_EquipInfo) GetStrengthenCount() int32 {
	if m != nil && m.StrengthenCount != nil {
		return *m.StrengthenCount
	}
	return 0
}

func (m *Game_EquipInfo) GetRefineCount() int32 {
	if m != nil && m.RefineCount != nil {
		return *m.RefineCount
	}
	return 0
}

func (m *Game_EquipInfo) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *Game_EquipInfo) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

type Game_EquipStruct struct {
	EquipInfo        *Game_EquipInfo   `protobuf:"bytes,1,opt,name=equip_info" json:"equip_info,omitempty"`
	Attribute        []*Game_Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_EquipStruct) Reset()         { *m = Game_EquipStruct{} }
func (m *Game_EquipStruct) String() string { return proto.CompactTextString(m) }
func (*Game_EquipStruct) ProtoMessage()    {}

func (m *Game_EquipStruct) GetEquipInfo() *Game_EquipInfo {
	if m != nil {
		return m.EquipInfo
	}
	return nil
}

func (m *Game_EquipStruct) GetAttribute() []*Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Game_MonsterAttr struct {
	Id               *int32            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid              *int32            `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Pos              *int32            `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	Level            *int32            `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	Hp               *int32            `protobuf:"varint,5,opt,name=hp" json:"hp,omitempty"`
	PhysicalAttack   *float32          `protobuf:"fixed32,6,opt,name=physical_attack" json:"physical_attack,omitempty"`
	MagicAttack      *float32          `protobuf:"fixed32,7,opt,name=magic_attack" json:"magic_attack,omitempty"`
	PhysicalDefense  *float32          `protobuf:"fixed32,8,opt,name=physical_defense" json:"physical_defense,omitempty"`
	MagicDefense     *float32          `protobuf:"fixed32,9,opt,name=magic_defense" json:"magic_defense,omitempty"`
	Speed            *int32            `protobuf:"varint,10,opt,name=speed" json:"speed,omitempty"`
	StepLevel        *int32            `protobuf:"varint,11,opt,name=step_level" json:"step_level,omitempty"`
	StarLevel        *int32            `protobuf:"varint,12,opt,name=star_level" json:"star_level,omitempty"`
	Name             *string           `protobuf:"bytes,13,opt,name=name" json:"name,omitempty"`
	Feature          *string           `protobuf:"bytes,14,opt,name=feature" json:"feature,omitempty"`
	Zodiac           *int32            `protobuf:"varint,15,opt,name=zodiac" json:"zodiac,omitempty"`
	Sex              *int32            `protobuf:"varint,16,opt,name=sex" json:"sex,omitempty"`
	Attribute        []*Game_Attribute `protobuf:"bytes,17,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_MonsterAttr) Reset()         { *m = Game_MonsterAttr{} }
func (m *Game_MonsterAttr) String() string { return proto.CompactTextString(m) }
func (*Game_MonsterAttr) ProtoMessage()    {}

func (m *Game_MonsterAttr) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_MonsterAttr) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Game_MonsterAttr) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *Game_MonsterAttr) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_MonsterAttr) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Game_MonsterAttr) GetPhysicalAttack() float32 {
	if m != nil && m.PhysicalAttack != nil {
		return *m.PhysicalAttack
	}
	return 0
}

func (m *Game_MonsterAttr) GetMagicAttack() float32 {
	if m != nil && m.MagicAttack != nil {
		return *m.MagicAttack
	}
	return 0
}

func (m *Game_MonsterAttr) GetPhysicalDefense() float32 {
	if m != nil && m.PhysicalDefense != nil {
		return *m.PhysicalDefense
	}
	return 0
}

func (m *Game_MonsterAttr) GetMagicDefense() float32 {
	if m != nil && m.MagicDefense != nil {
		return *m.MagicDefense
	}
	return 0
}

func (m *Game_MonsterAttr) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Game_MonsterAttr) GetStepLevel() int32 {
	if m != nil && m.StepLevel != nil {
		return *m.StepLevel
	}
	return 0
}

func (m *Game_MonsterAttr) GetStarLevel() int32 {
	if m != nil && m.StarLevel != nil {
		return *m.StarLevel
	}
	return 0
}

func (m *Game_MonsterAttr) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Game_MonsterAttr) GetFeature() string {
	if m != nil && m.Feature != nil {
		return *m.Feature
	}
	return ""
}

func (m *Game_MonsterAttr) GetZodiac() int32 {
	if m != nil && m.Zodiac != nil {
		return *m.Zodiac
	}
	return 0
}

func (m *Game_MonsterAttr) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *Game_MonsterAttr) GetAttribute() []*Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Game_MonsterCombatTeam struct {
	MonsterAttrs     []*Game_MonsterAttr `protobuf:"bytes,1,rep,name=monster_attrs" json:"monster_attrs,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_MonsterCombatTeam) Reset()         { *m = Game_MonsterCombatTeam{} }
func (m *Game_MonsterCombatTeam) String() string { return proto.CompactTextString(m) }
func (*Game_MonsterCombatTeam) ProtoMessage()    {}

func (m *Game_MonsterCombatTeam) GetMonsterAttrs() []*Game_MonsterAttr {
	if m != nil {
		return m.MonsterAttrs
	}
	return nil
}

type Game_StageBaseDrop struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Id               *int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Count            *int32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_StageBaseDrop) Reset()         { *m = Game_StageBaseDrop{} }
func (m *Game_StageBaseDrop) String() string { return proto.CompactTextString(m) }
func (*Game_StageBaseDrop) ProtoMessage()    {}

func (m *Game_StageBaseDrop) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_StageBaseDrop) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_StageBaseDrop) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type Game_StageBossDrop struct {
	Conditions       []int32 `protobuf:"varint,1,rep,name=conditions" json:"conditions,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_StageBossDrop) Reset()         { *m = Game_StageBossDrop{} }
func (m *Game_StageBossDrop) String() string { return proto.CompactTextString(m) }
func (*Game_StageBossDrop) ProtoMessage()    {}

func (m *Game_StageBossDrop) GetConditions() []int32 {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type Game_Stage struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	State            *int32 `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	StageId          *int32 `protobuf:"varint,3,opt,name=stage_id" json:"stage_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Stage) Reset()         { *m = Game_Stage{} }
func (m *Game_Stage) String() string { return proto.CompactTextString(m) }
func (*Game_Stage) ProtoMessage()    {}

func (m *Game_Stage) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Stage) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *Game_Stage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

// pid = 1001	客户端发送注册角色信息
type Game_RegisterRole struct {
	PlayerId         *int32  `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	Nick             *string `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	HeroId           *int32  `protobuf:"varint,3,opt,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_RegisterRole) Reset()         { *m = Game_RegisterRole{} }
func (m *Game_RegisterRole) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRole) ProtoMessage()    {}

func (m *Game_RegisterRole) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *Game_RegisterRole) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Game_RegisterRole) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

// pid = 1001 服务器返回 角色注册信息
type Game_RegisterRoleResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_RegisterRoleResult) Reset()         { *m = Game_RegisterRoleResult{} }
func (m *Game_RegisterRoleResult) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRoleResult) ProtoMessage()    {}

func (m *Game_RegisterRoleResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// pid = 1002 获取角色信息
type Game_GetRoleInfo struct {
	PlayerId         *int32 `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_GetRoleInfo) Reset()         { *m = Game_GetRoleInfo{} }
func (m *Game_GetRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_GetRoleInfo) ProtoMessage()    {}

func (m *Game_GetRoleInfo) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// pid = 1002 角色返回
type Game_RoleInfoResult struct {
	IsCreate   *bool            `protobuf:"varint,1,opt,name=is_create" json:"is_create,omitempty"`
	PlayerInfo *Game_PlayerInfo `protobuf:"bytes,2,opt,name=player_info" json:"player_info,omitempty"`
	// repeated FormationStruct formation_struct = 3;//阵型(发送1023)
	HeroStruct []*Game_HeroStruct `protobuf:"bytes,4,rep,name=hero_struct" json:"hero_struct,omitempty"`
	// repeated PropStruct prop_struct = 5;//道具相关
	// repeated EquipStruct equip_struct = 6;//所有装备列表
	CopyLevels       []*Game_Stage `protobuf:"bytes,7,rep,name=copy_levels" json:"copy_levels,omitempty"`
	HangupLevels     []*Game_Stage `protobuf:"bytes,8,rep,name=hangup_levels" json:"hangup_levels,omitempty"`
	ProfessionId     *int32        `protobuf:"varint,9,opt,name=profession_id" json:"profession_id,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Game_RoleInfoResult) Reset()         { *m = Game_RoleInfoResult{} }
func (m *Game_RoleInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_RoleInfoResult) ProtoMessage()    {}

func (m *Game_RoleInfoResult) GetIsCreate() bool {
	if m != nil && m.IsCreate != nil {
		return *m.IsCreate
	}
	return false
}

func (m *Game_RoleInfoResult) GetPlayerInfo() *Game_PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Game_RoleInfoResult) GetHeroStruct() []*Game_HeroStruct {
	if m != nil {
		return m.HeroStruct
	}
	return nil
}

func (m *Game_RoleInfoResult) GetCopyLevels() []*Game_Stage {
	if m != nil {
		return m.CopyLevels
	}
	return nil
}

func (m *Game_RoleInfoResult) GetHangupLevels() []*Game_Stage {
	if m != nil {
		return m.HangupLevels
	}
	return nil
}

func (m *Game_RoleInfoResult) GetProfessionId() int32 {
	if m != nil && m.ProfessionId != nil {
		return *m.ProfessionId
	}
	return 0
}

// pid = 1003 关卡挑战
type Game_WarMapStage struct {
	StageId          *int32 `protobuf:"varint,1,opt,name=stage_id" json:"stage_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_WarMapStage) Reset()         { *m = Game_WarMapStage{} }
func (m *Game_WarMapStage) String() string { return proto.CompactTextString(m) }
func (*Game_WarMapStage) ProtoMessage()    {}

func (m *Game_WarMapStage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

// pid = 1003 战斗是否允许 阵容(后期添加) 返回
type Game_MapStageResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_MapStageResult) Reset()         { *m = Game_MapStageResult{} }
func (m *Game_MapStageResult) String() string { return proto.CompactTextString(m) }
func (*Game_MapStageResult) ProtoMessage()    {}

func (m *Game_MapStageResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type Game_RwardProp struct {
	PropUid          *int32 `protobuf:"varint,1,opt,name=prop_uid" json:"prop_uid,omitempty"`
	Num              *int32 `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_RwardProp) Reset()         { *m = Game_RwardProp{} }
func (m *Game_RwardProp) String() string { return proto.CompactTextString(m) }
func (*Game_RwardProp) ProtoMessage()    {}

func (m *Game_RwardProp) GetPropUid() int32 {
	if m != nil && m.PropUid != nil {
		return *m.PropUid
	}
	return 0
}

func (m *Game_RwardProp) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type Game_Reward struct {
	PlayerExp        *int32            `protobuf:"varint,1,opt,name=player_exp" json:"player_exp,omitempty"`
	PlayerGold       *int32            `protobuf:"varint,2,opt,name=player_gold" json:"player_gold,omitempty"`
	HeroExp          *int32            `protobuf:"varint,3,opt,name=hero_exp" json:"hero_exp,omitempty"`
	EquipUids        []int32           `protobuf:"varint,4,rep,name=equip_uids" json:"equip_uids,omitempty"`
	PropUids         []*Game_RwardProp `protobuf:"bytes,5,rep,name=prop_uids" json:"prop_uids,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_Reward) Reset()         { *m = Game_Reward{} }
func (m *Game_Reward) String() string { return proto.CompactTextString(m) }
func (*Game_Reward) ProtoMessage()    {}

func (m *Game_Reward) GetPlayerExp() int32 {
	if m != nil && m.PlayerExp != nil {
		return *m.PlayerExp
	}
	return 0
}

func (m *Game_Reward) GetPlayerGold() int32 {
	if m != nil && m.PlayerGold != nil {
		return *m.PlayerGold
	}
	return 0
}

func (m *Game_Reward) GetHeroExp() int32 {
	if m != nil && m.HeroExp != nil {
		return *m.HeroExp
	}
	return 0
}

func (m *Game_Reward) GetEquipUids() []int32 {
	if m != nil {
		return m.EquipUids
	}
	return nil
}

func (m *Game_Reward) GetPropUids() []*Game_RwardProp {
	if m != nil {
		return m.PropUids
	}
	return nil
}

// pid = 1004 战斗结果客户的通知服务器
type Game_WarMapNoteServer struct {
	Stage            *Game_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_WarMapNoteServer) Reset()         { *m = Game_WarMapNoteServer{} }
func (m *Game_WarMapNoteServer) String() string { return proto.CompactTextString(m) }
func (*Game_WarMapNoteServer) ProtoMessage()    {}

func (m *Game_WarMapNoteServer) GetStage() *Game_Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

// pid = 1004 战斗结果客户的通知服务器 result
type Game_WarMapNoteServerResult struct {
	Reward           *Game_Reward `protobuf:"bytes,1,opt,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_WarMapNoteServerResult) Reset()         { *m = Game_WarMapNoteServerResult{} }
func (m *Game_WarMapNoteServerResult) String() string { return proto.CompactTextString(m) }
func (*Game_WarMapNoteServerResult) ProtoMessage()    {}

func (m *Game_WarMapNoteServerResult) GetReward() *Game_Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

// pid = 1005 扫荡
type Game_SweepMapStage struct {
	StageId          *int32 `protobuf:"varint,1,opt,name=stage_id" json:"stage_id,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_SweepMapStage) Reset()         { *m = Game_SweepMapStage{} }
func (m *Game_SweepMapStage) String() string { return proto.CompactTextString(m) }
func (*Game_SweepMapStage) ProtoMessage()    {}

func (m *Game_SweepMapStage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

func (m *Game_SweepMapStage) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// pid = 1005 扫荡 result
type Game_SweepMapStageResult struct {
	Result           *int32         `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Reward           []*Game_Reward `protobuf:"bytes,2,rep,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Game_SweepMapStageResult) Reset()         { *m = Game_SweepMapStageResult{} }
func (m *Game_SweepMapStageResult) String() string { return proto.CompactTextString(m) }
func (*Game_SweepMapStageResult) ProtoMessage()    {}

func (m *Game_SweepMapStageResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Game_SweepMapStageResult) GetReward() []*Game_Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

// pid = 1006 服务器主动通知客户端 背包中道具变化(such as:掉落时候 )
type Game_Notice2CProp struct {
	Type             *int32             `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Prop             []*Game_PropStruct `protobuf:"bytes,2,rep,name=prop" json:"prop,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_Notice2CProp) Reset()         { *m = Game_Notice2CProp{} }
func (m *Game_Notice2CProp) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CProp) ProtoMessage()    {}

func (m *Game_Notice2CProp) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Notice2CProp) GetProp() []*Game_PropStruct {
	if m != nil {
		return m.Prop
	}
	return nil
}

// pid = 1008 服务器主动背包中装备变化通知客户端(such as:掉落时候 )1006类似
type Game_Notice2CEquip struct {
	Type             *int32              `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Equip            []*Game_EquipStruct `protobuf:"bytes,2,rep,name=equip" json:"equip,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_Notice2CEquip) Reset()         { *m = Game_Notice2CEquip{} }
func (m *Game_Notice2CEquip) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CEquip) ProtoMessage()    {}

func (m *Game_Notice2CEquip) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Notice2CEquip) GetEquip() []*Game_EquipStruct {
	if m != nil {
		return m.Equip
	}
	return nil
}

// pid = 1010 服务器通知客户端玩家基础属性变化
type Game_Notice2CRoleInfo struct {
	Level            *int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp              *int32 `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Power            *int32 `protobuf:"varint,3,opt,name=power" json:"power,omitempty"`
	Hp               *int32 `protobuf:"varint,4,opt,name=hp" json:"hp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CRoleInfo) Reset()         { *m = Game_Notice2CRoleInfo{} }
func (m *Game_Notice2CRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CRoleInfo) ProtoMessage()    {}

func (m *Game_Notice2CRoleInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_Notice2CRoleInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_Notice2CRoleInfo) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Game_Notice2CRoleInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

// pid = 1011 钱变化
type Game_Notice2CMoney struct {
	Gold             *int32 `protobuf:"varint,1,opt,name=gold" json:"gold,omitempty"`
	Diamond          *int32 `protobuf:"varint,2,opt,name=diamond" json:"diamond,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CMoney) Reset()         { *m = Game_Notice2CMoney{} }
func (m *Game_Notice2CMoney) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CMoney) ProtoMessage()    {}

func (m *Game_Notice2CMoney) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_Notice2CMoney) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

// pid = 1012 体力变化
type Game_Notice2CEnergy struct {
	Energy           *int32 `protobuf:"varint,1,opt,name=energy" json:"energy,omitempty"`
	EnergyMax        *int32 `protobuf:"varint,2,opt,name=energy_max" json:"energy_max,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CEnergy) Reset()         { *m = Game_Notice2CEnergy{} }
func (m *Game_Notice2CEnergy) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CEnergy) ProtoMessage()    {}

func (m *Game_Notice2CEnergy) GetEnergy() int32 {
	if m != nil && m.Energy != nil {
		return *m.Energy
	}
	return 0
}

func (m *Game_Notice2CEnergy) GetEnergyMax() int32 {
	if m != nil && m.EnergyMax != nil {
		return *m.EnergyMax
	}
	return 0
}

// pid = 1013 关卡变化
type Game_Notice2CheckPoint struct {
	LatestCheckpoint *Game_Stage `protobuf:"bytes,1,opt,name=latest_checkpoint" json:"latest_checkpoint,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_Notice2CheckPoint) Reset()         { *m = Game_Notice2CheckPoint{} }
func (m *Game_Notice2CheckPoint) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CheckPoint) ProtoMessage()    {}

func (m *Game_Notice2CheckPoint) GetLatestCheckpoint() *Game_Stage {
	if m != nil {
		return m.LatestCheckpoint
	}
	return nil
}

// pid = 1014 离线挂机收益
type Game_OffNotice2CGuaji struct {
	PointId          *int32            `protobuf:"varint,1,opt,name=point_id" json:"point_id,omitempty"`
	Gold             *int32            `protobuf:"varint,2,opt,name=gold" json:"gold,omitempty"`
	Exp              *int32            `protobuf:"varint,3,opt,name=exp" json:"exp,omitempty"`
	GuajiTime        *int32            `protobuf:"varint,4,opt,name=guaji_time" json:"guaji_time,omitempty"`
	KillNpcNum       *int32            `protobuf:"varint,5,opt,name=kill_npc_num" json:"kill_npc_num,omitempty"`
	EquipUids        []int32           `protobuf:"varint,6,rep,name=equip_uids" json:"equip_uids,omitempty"`
	PropUids         []*Game_RwardProp `protobuf:"bytes,7,rep,name=prop_uids" json:"prop_uids,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_OffNotice2CGuaji) Reset()         { *m = Game_OffNotice2CGuaji{} }
func (m *Game_OffNotice2CGuaji) String() string { return proto.CompactTextString(m) }
func (*Game_OffNotice2CGuaji) ProtoMessage()    {}

func (m *Game_OffNotice2CGuaji) GetPointId() int32 {
	if m != nil && m.PointId != nil {
		return *m.PointId
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetGuajiTime() int32 {
	if m != nil && m.GuajiTime != nil {
		return *m.GuajiTime
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetKillNpcNum() int32 {
	if m != nil && m.KillNpcNum != nil {
		return *m.KillNpcNum
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetEquipUids() []int32 {
	if m != nil {
		return m.EquipUids
	}
	return nil
}

func (m *Game_OffNotice2CGuaji) GetPropUids() []*Game_RwardProp {
	if m != nil {
		return m.PropUids
	}
	return nil
}

// pid = 1015 在线挂机收益c2s
type Game_C2SOnlineGuaji struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_C2SOnlineGuaji) Reset()         { *m = Game_C2SOnlineGuaji{} }
func (m *Game_C2SOnlineGuaji) String() string { return proto.CompactTextString(m) }
func (*Game_C2SOnlineGuaji) ProtoMessage()    {}

// pid = 1015 在线挂机收益 result
type Game_OnNotice2CGuaji struct {
	GuajiType        *int32            `protobuf:"varint,1,opt,name=guaji_type" json:"guaji_type,omitempty"`
	NpcId            *int32            `protobuf:"varint,2,opt,name=npc_id" json:"npc_id,omitempty"`
	Gold             *int32            `protobuf:"varint,3,opt,name=gold" json:"gold,omitempty"`
	Exp              *int32            `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	EquipUids        []int32           `protobuf:"varint,5,rep,name=equip_uids" json:"equip_uids,omitempty"`
	PropUids         []*Game_RwardProp `protobuf:"bytes,6,rep,name=prop_uids" json:"prop_uids,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_OnNotice2CGuaji) Reset()         { *m = Game_OnNotice2CGuaji{} }
func (m *Game_OnNotice2CGuaji) String() string { return proto.CompactTextString(m) }
func (*Game_OnNotice2CGuaji) ProtoMessage()    {}

func (m *Game_OnNotice2CGuaji) GetGuajiType() int32 {
	if m != nil && m.GuajiType != nil {
		return *m.GuajiType
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetNpcId() int32 {
	if m != nil && m.NpcId != nil {
		return *m.NpcId
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetEquipUids() []int32 {
	if m != nil {
		return m.EquipUids
	}
	return nil
}

func (m *Game_OnNotice2CGuaji) GetPropUids() []*Game_RwardProp {
	if m != nil {
		return m.PropUids
	}
	return nil
}

type Game_Conditions struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	CurCount         *int32 `protobuf:"varint,3,opt,name=cur_count" json:"cur_count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Conditions) Reset()         { *m = Game_Conditions{} }
func (m *Game_Conditions) String() string { return proto.CompactTextString(m) }
func (*Game_Conditions) ProtoMessage()    {}

func (m *Game_Conditions) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Conditions) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *Game_Conditions) GetCurCount() int32 {
	if m != nil && m.CurCount != nil {
		return *m.CurCount
	}
	return 0
}

// pid = 1016 C2S 请求挂机信息
type GameGetGuajiInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameGetGuajiInfo) Reset()         { *m = GameGetGuajiInfo{} }
func (m *GameGetGuajiInfo) String() string { return proto.CompactTextString(m) }
func (*GameGetGuajiInfo) ProtoMessage()    {}

func (m *GameGetGuajiInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// pid = 1016 请求挂机 返回
type Game_GuajiInfoResult struct {
	Conditions       []*Game_Conditions `protobuf:"bytes,1,rep,name=conditions" json:"conditions,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_GuajiInfoResult) Reset()         { *m = Game_GuajiInfoResult{} }
func (m *Game_GuajiInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_GuajiInfoResult) ProtoMessage()    {}

func (m *Game_GuajiInfoResult) GetConditions() []*Game_Conditions {
	if m != nil {
		return m.Conditions
	}
	return nil
}

// pid = 1017 C2S boss挑战 队伍请求
type Game_ChallengeBoss struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChallengeBoss) Reset()         { *m = Game_ChallengeBoss{} }
func (m *Game_ChallengeBoss) String() string { return proto.CompactTextString(m) }
func (*Game_ChallengeBoss) ProtoMessage()    {}

func (m *Game_ChallengeBoss) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// pid = 1017 挑战 队伍请求 返回
type Game_ChallengeBossResult struct {
	IsCanChange *bool `protobuf:"varint,1,opt,name=is_can_change" json:"is_can_change,omitempty"`
	// repeated HeroStruct team_1 = 2;//队一(自己)
	Team_2           *Game_MonsterCombatTeam `protobuf:"bytes,3,opt,name=team_2" json:"team_2,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Game_ChallengeBossResult) Reset()         { *m = Game_ChallengeBossResult{} }
func (m *Game_ChallengeBossResult) String() string { return proto.CompactTextString(m) }
func (*Game_ChallengeBossResult) ProtoMessage()    {}

func (m *Game_ChallengeBossResult) GetIsCanChange() bool {
	if m != nil && m.IsCanChange != nil {
		return *m.IsCanChange
	}
	return false
}

func (m *Game_ChallengeBossResult) GetTeam_2() *Game_MonsterCombatTeam {
	if m != nil {
		return m.Team_2
	}
	return nil
}

// pid = 1018 客户端通知服务器boss挑战结果
type Game_C2SChallenge struct {
	Stage            *Game_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_C2SChallenge) Reset()         { *m = Game_C2SChallenge{} }
func (m *Game_C2SChallenge) String() string { return proto.CompactTextString(m) }
func (*Game_C2SChallenge) ProtoMessage()    {}

func (m *Game_C2SChallenge) GetStage() *Game_Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

// pid = 1018 服务器返回boss 奖励
type Game_C2SChallengeResult struct {
	EquipUids        []int32           `protobuf:"varint,1,rep,name=equip_uids" json:"equip_uids,omitempty"`
	PropUids         []*Game_RwardProp `protobuf:"bytes,2,rep,name=prop_uids" json:"prop_uids,omitempty"`
	HeroExp          *int32            `protobuf:"varint,3,opt,name=hero_exp" json:"hero_exp,omitempty"`
	RoleExp          *int32            `protobuf:"varint,4,opt,name=role_exp" json:"role_exp,omitempty"`
	Gold             *int32            `protobuf:"varint,5,opt,name=gold" json:"gold,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_C2SChallengeResult) Reset()         { *m = Game_C2SChallengeResult{} }
func (m *Game_C2SChallengeResult) String() string { return proto.CompactTextString(m) }
func (*Game_C2SChallengeResult) ProtoMessage()    {}

func (m *Game_C2SChallengeResult) GetEquipUids() []int32 {
	if m != nil {
		return m.EquipUids
	}
	return nil
}

func (m *Game_C2SChallengeResult) GetPropUids() []*Game_RwardProp {
	if m != nil {
		return m.PropUids
	}
	return nil
}

func (m *Game_C2SChallengeResult) GetHeroExp() int32 {
	if m != nil && m.HeroExp != nil {
		return *m.HeroExp
	}
	return 0
}

func (m *Game_C2SChallengeResult) GetRoleExp() int32 {
	if m != nil && m.RoleExp != nil {
		return *m.RoleExp
	}
	return 0
}

func (m *Game_C2SChallengeResult) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

// pid 1019 客户端通知服务器退出
type Game_LoginOut struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_LoginOut) Reset()         { *m = Game_LoginOut{} }
func (m *Game_LoginOut) String() string { return proto.CompactTextString(m) }
func (*Game_LoginOut) ProtoMessage()    {}

// pid = 1020 C2S 切换关卡
type Game_ChangeGuajiInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChangeGuajiInfo) Reset()         { *m = Game_ChangeGuajiInfo{} }
func (m *Game_ChangeGuajiInfo) String() string { return proto.CompactTextString(m) }
func (*Game_ChangeGuajiInfo) ProtoMessage()    {}

func (m *Game_ChangeGuajiInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// pid = 1020 C2S 切换关卡 result
type Game_ChangeGuajiInfoResult struct {
	IsOk             *bool  `protobuf:"varint,1,opt,name=is_ok" json:"is_ok,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChangeGuajiInfoResult) Reset()         { *m = Game_ChangeGuajiInfoResult{} }
func (m *Game_ChangeGuajiInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_ChangeGuajiInfoResult) ProtoMessage()    {}

func (m *Game_ChangeGuajiInfoResult) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return false
}

// pid = 1021 快速战斗
type Game_FastWar struct {
	Stage            *Game_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_FastWar) Reset()         { *m = Game_FastWar{} }
func (m *Game_FastWar) String() string { return proto.CompactTextString(m) }
func (*Game_FastWar) ProtoMessage()    {}

func (m *Game_FastWar) GetStage() *Game_Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

// pid = 1021 快速战斗 result
type Game_FastWarResult struct {
	Result           *int32       `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Reward           *Game_Reward `protobuf:"bytes,2,opt,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_FastWarResult) Reset()         { *m = Game_FastWarResult{} }
func (m *Game_FastWarResult) String() string { return proto.CompactTextString(m) }
func (*Game_FastWarResult) ProtoMessage()    {}

func (m *Game_FastWarResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Game_FastWarResult) GetReward() *Game_Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

// pid = 1022 获取玩家当前挂机列表
type Game_GetGuajiRoleList struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_GetGuajiRoleList) Reset()         { *m = Game_GetGuajiRoleList{} }
func (m *Game_GetGuajiRoleList) String() string { return proto.CompactTextString(m) }
func (*Game_GetGuajiRoleList) ProtoMessage()    {}

// 挂机玩家消息
type Game_GuajiRoleInfo struct {
	PkType           *int32  `protobuf:"varint,1,opt,name=pk_type" json:"pk_type,omitempty"`
	ProtectTime      *int32  `protobuf:"varint,2,opt,name=protect_time" json:"protect_time,omitempty"`
	LastPkNum        *int32  `protobuf:"varint,3,opt,name=last_pk_num" json:"last_pk_num,omitempty"`
	KillNum          *int32  `protobuf:"varint,4,opt,name=kill_num" json:"kill_num,omitempty"`
	RoleId           *int64  `protobuf:"varint,5,opt,name=role_id" json:"role_id,omitempty"`
	ProfessionId     *int32  `protobuf:"varint,6,opt,name=profession_id" json:"profession_id,omitempty"`
	Level            *int32  `protobuf:"varint,7,opt,name=level" json:"level,omitempty"`
	Power            *int32  `protobuf:"varint,8,opt,name=power" json:"power,omitempty"`
	Nick             *string `protobuf:"bytes,9,opt,name=nick" json:"nick,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_GuajiRoleInfo) Reset()         { *m = Game_GuajiRoleInfo{} }
func (m *Game_GuajiRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_GuajiRoleInfo) ProtoMessage()    {}

func (m *Game_GuajiRoleInfo) GetPkType() int32 {
	if m != nil && m.PkType != nil {
		return *m.PkType
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetProtectTime() int32 {
	if m != nil && m.ProtectTime != nil {
		return *m.ProtectTime
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetLastPkNum() int32 {
	if m != nil && m.LastPkNum != nil {
		return *m.LastPkNum
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetKillNum() int32 {
	if m != nil && m.KillNum != nil {
		return *m.KillNum
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetRoleId() int64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetProfessionId() int32 {
	if m != nil && m.ProfessionId != nil {
		return *m.ProfessionId
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Game_GuajiRoleInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

// 1022 挂机玩家列表 返回
type Game_GetGuajiRoleListResult struct {
	GuajiRoleInfos   []*Game_GuajiRoleInfo `protobuf:"bytes,1,rep,name=guaji_role_infos" json:"guaji_role_infos,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Game_GetGuajiRoleListResult) Reset()         { *m = Game_GetGuajiRoleListResult{} }
func (m *Game_GetGuajiRoleListResult) String() string { return proto.CompactTextString(m) }
func (*Game_GetGuajiRoleListResult) ProtoMessage()    {}

func (m *Game_GetGuajiRoleListResult) GetGuajiRoleInfos() []*Game_GuajiRoleInfo {
	if m != nil {
		return m.GuajiRoleInfos
	}
	return nil
}

// 1023 请求对应角色阵型
type Game_GetGuajiRoleFormation struct {
	RoleId           *int64 `protobuf:"varint,1,opt,name=role_id" json:"role_id,omitempty"`
	Type             *int32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_GetGuajiRoleFormation) Reset()         { *m = Game_GetGuajiRoleFormation{} }
func (m *Game_GetGuajiRoleFormation) String() string { return proto.CompactTextString(m) }
func (*Game_GetGuajiRoleFormation) ProtoMessage()    {}

func (m *Game_GetGuajiRoleFormation) GetRoleId() int64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *Game_GetGuajiRoleFormation) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 1023 请求对应role阵型 返回
type Game_GetGuajiRoleFormationResult struct {
	Type             *int32                  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Result           *int32                  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	Formations       []*Game_FormationStruct `protobuf:"bytes,3,rep,name=formations" json:"formations,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Game_GetGuajiRoleFormationResult) Reset()         { *m = Game_GetGuajiRoleFormationResult{} }
func (m *Game_GetGuajiRoleFormationResult) String() string { return proto.CompactTextString(m) }
func (*Game_GetGuajiRoleFormationResult) ProtoMessage()    {}

func (m *Game_GetGuajiRoleFormationResult) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_GetGuajiRoleFormationResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Game_GetGuajiRoleFormationResult) GetFormations() []*Game_FormationStruct {
	if m != nil {
		return m.Formations
	}
	return nil
}

// 1024 英雄上阵 下阵
type Game_HerosFormation struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	IsOn             *bool  `protobuf:"varint,2,opt,name=is_on" json:"is_on,omitempty"`
	PosId            *int32 `protobuf:"varint,3,opt,name=pos_id" json:"pos_id,omitempty"`
	HeroUid          *int32 `protobuf:"varint,4,opt,name=hero_uid" json:"hero_uid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_HerosFormation) Reset()         { *m = Game_HerosFormation{} }
func (m *Game_HerosFormation) String() string { return proto.CompactTextString(m) }
func (*Game_HerosFormation) ProtoMessage()    {}

func (m *Game_HerosFormation) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_HerosFormation) GetIsOn() bool {
	if m != nil && m.IsOn != nil {
		return *m.IsOn
	}
	return false
}

func (m *Game_HerosFormation) GetPosId() int32 {
	if m != nil && m.PosId != nil {
		return *m.PosId
	}
	return 0
}

func (m *Game_HerosFormation) GetHeroUid() int32 {
	if m != nil && m.HeroUid != nil {
		return *m.HeroUid
	}
	return 0
}

// 1024 英雄上阵 下阵 返回
type Game_HerosFormationResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_HerosFormationResult) Reset()         { *m = Game_HerosFormationResult{} }
func (m *Game_HerosFormationResult) String() string { return proto.CompactTextString(m) }
func (*Game_HerosFormationResult) ProtoMessage()    {}

func (m *Game_HerosFormationResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 1025 位置交换
type Game_ChangeHerosFormation struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	PosId_1          *int32 `protobuf:"varint,2,opt,name=pos_id_1" json:"pos_id_1,omitempty"`
	PosId_2          *int32 `protobuf:"varint,3,opt,name=pos_id_2" json:"pos_id_2,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChangeHerosFormation) Reset()         { *m = Game_ChangeHerosFormation{} }
func (m *Game_ChangeHerosFormation) String() string { return proto.CompactTextString(m) }
func (*Game_ChangeHerosFormation) ProtoMessage()    {}

func (m *Game_ChangeHerosFormation) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_ChangeHerosFormation) GetPosId_1() int32 {
	if m != nil && m.PosId_1 != nil {
		return *m.PosId_1
	}
	return 0
}

func (m *Game_ChangeHerosFormation) GetPosId_2() int32 {
	if m != nil && m.PosId_2 != nil {
		return *m.PosId_2
	}
	return 0
}

// 1025 位置交换 返回
type Game_ChangeHerosFormationResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChangeHerosFormationResult) Reset()         { *m = Game_ChangeHerosFormationResult{} }
func (m *Game_ChangeHerosFormationResult) String() string { return proto.CompactTextString(m) }
func (*Game_ChangeHerosFormationResult) ProtoMessage()    {}

func (m *Game_ChangeHerosFormationResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// pid = 1026 C2S 挑战其他玩家
type Game_ChallengePlayer struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	RoleId           *int64 `protobuf:"varint,2,opt,name=role_id" json:"role_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChallengePlayer) Reset()         { *m = Game_ChallengePlayer{} }
func (m *Game_ChallengePlayer) String() string { return proto.CompactTextString(m) }
func (*Game_ChallengePlayer) ProtoMessage()    {}

func (m *Game_ChallengePlayer) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_ChallengePlayer) GetRoleId() int64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

// pid = 1026 挑战其他玩家 返回
type Game_ChallengePlayerResult struct {
	IsCanChange *bool `protobuf:"varint,1,opt,name=is_can_change" json:"is_can_change,omitempty"`
	// repeated HeroStruct team_1 = 2;//队一(自己)
	Team_2           []*Game_HeroStruct `protobuf:"bytes,3,rep,name=team_2" json:"team_2,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_ChallengePlayerResult) Reset()         { *m = Game_ChallengePlayerResult{} }
func (m *Game_ChallengePlayerResult) String() string { return proto.CompactTextString(m) }
func (*Game_ChallengePlayerResult) ProtoMessage()    {}

func (m *Game_ChallengePlayerResult) GetIsCanChange() bool {
	if m != nil && m.IsCanChange != nil {
		return *m.IsCanChange
	}
	return false
}

func (m *Game_ChallengePlayerResult) GetTeam_2() []*Game_HeroStruct {
	if m != nil {
		return m.Team_2
	}
	return nil
}

// pid = 1027 使用某道具
type Game_UseProp struct {
	Uid              *int32 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_UseProp) Reset()         { *m = Game_UseProp{} }
func (m *Game_UseProp) String() string { return proto.CompactTextString(m) }
func (*Game_UseProp) ProtoMessage()    {}

func (m *Game_UseProp) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Game_UseProp) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// pid = 1027 使用某道具 返回
type Game_UsePropResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_UsePropResult) Reset()         { *m = Game_UsePropResult{} }
func (m *Game_UsePropResult) String() string { return proto.CompactTextString(m) }
func (*Game_UsePropResult) ProtoMessage()    {}

func (m *Game_UsePropResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// pid = 1028 服务器通知客户端消息
type Game_Notice2CMsg struct {
	Msg              *int32 `protobuf:"varint,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CMsg) Reset()         { *m = Game_Notice2CMsg{} }
func (m *Game_Notice2CMsg) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CMsg) ProtoMessage()    {}

func (m *Game_Notice2CMsg) GetMsg() int32 {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return 0
}

// pid = 1029 查看道具背包
type Game_CheckPropBag struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_CheckPropBag) Reset()         { *m = Game_CheckPropBag{} }
func (m *Game_CheckPropBag) String() string { return proto.CompactTextString(m) }
func (*Game_CheckPropBag) ProtoMessage()    {}

// pid = 1029 查看道具背包 返回
type Game_CheckPropBagResult struct {
	PropStruct       []*Game_PropStruct `protobuf:"bytes,1,rep,name=prop_struct" json:"prop_struct,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_CheckPropBagResult) Reset()         { *m = Game_CheckPropBagResult{} }
func (m *Game_CheckPropBagResult) String() string { return proto.CompactTextString(m) }
func (*Game_CheckPropBagResult) ProtoMessage()    {}

func (m *Game_CheckPropBagResult) GetPropStruct() []*Game_PropStruct {
	if m != nil {
		return m.PropStruct
	}
	return nil
}

// pid = 1030 查看道具背包
type Game_CheckEquipBag struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_CheckEquipBag) Reset()         { *m = Game_CheckEquipBag{} }
func (m *Game_CheckEquipBag) String() string { return proto.CompactTextString(m) }
func (*Game_CheckEquipBag) ProtoMessage()    {}

// pid = 1030 查看道具背包 返回
type Game_CheckEquipBagResult struct {
	EquipStruct      []*Game_EquipStruct `protobuf:"bytes,1,rep,name=equip_struct" json:"equip_struct,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_CheckEquipBagResult) Reset()         { *m = Game_CheckEquipBagResult{} }
func (m *Game_CheckEquipBagResult) String() string { return proto.CompactTextString(m) }
func (*Game_CheckEquipBagResult) ProtoMessage()    {}

func (m *Game_CheckEquipBagResult) GetEquipStruct() []*Game_EquipStruct {
	if m != nil {
		return m.EquipStruct
	}
	return nil
}
