// Code generated by protoc-gen-go.
// source: Game.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	Game.proto

It has these top-level messages:
	Game
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Game struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}

type Game_PlayerInfo struct {
	Level             *int32  `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp               *int32  `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Hp                *int32  `protobuf:"varint,3,opt,name=hp" json:"hp,omitempty"`
	Energy            *int32  `protobuf:"varint,4,opt,name=energy" json:"energy,omitempty"`
	EnergyMax         *int32  `protobuf:"varint,5,opt,name=energy_max" json:"energy_max,omitempty"`
	Vip               *int32  `protobuf:"varint,6,opt,name=vip" json:"vip,omitempty"`
	Gold              *int32  `protobuf:"varint,7,opt,name=gold" json:"gold,omitempty"`
	Diamond           *int32  `protobuf:"varint,8,opt,name=diamond" json:"diamond,omitempty"`
	Power             *int32  `protobuf:"varint,9,opt,name=power" json:"power,omitempty"`
	Nick              *string `protobuf:"bytes,10,opt,name=nick" json:"nick,omitempty"`
	Signature         *string `protobuf:"bytes,11,opt,name=signature" json:"signature,omitempty"`
	Option            []bool  `protobuf:"varint,12,rep,name=option" json:"option,omitempty"`
	SignDays          *int32  `protobuf:"varint,13,opt,name=sign_days" json:"sign_days,omitempty"`
	AchievementPoints *int32  `protobuf:"varint,14,opt,name=achievement_points" json:"achievement_points,omitempty"`
	TaskPoints        *int32  `protobuf:"varint,15,opt,name=task_points" json:"task_points,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Game_PlayerInfo) Reset()         { *m = Game_PlayerInfo{} }
func (m *Game_PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*Game_PlayerInfo) ProtoMessage()    {}

func (m *Game_PlayerInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_PlayerInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_PlayerInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Game_PlayerInfo) GetEnergy() int32 {
	if m != nil && m.Energy != nil {
		return *m.Energy
	}
	return 0
}

func (m *Game_PlayerInfo) GetEnergyMax() int32 {
	if m != nil && m.EnergyMax != nil {
		return *m.EnergyMax
	}
	return 0
}

func (m *Game_PlayerInfo) GetVip() int32 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *Game_PlayerInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_PlayerInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

func (m *Game_PlayerInfo) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Game_PlayerInfo) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Game_PlayerInfo) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *Game_PlayerInfo) GetOption() []bool {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *Game_PlayerInfo) GetSignDays() int32 {
	if m != nil && m.SignDays != nil {
		return *m.SignDays
	}
	return 0
}

func (m *Game_PlayerInfo) GetAchievementPoints() int32 {
	if m != nil && m.AchievementPoints != nil {
		return *m.AchievementPoints
	}
	return 0
}

func (m *Game_PlayerInfo) GetTaskPoints() int32 {
	if m != nil && m.TaskPoints != nil {
		return *m.TaskPoints
	}
	return 0
}

type Game_HeroInfo struct {
	Level            *int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp              *int32 `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Hp               *int32 `protobuf:"varint,3,opt,name=hp" json:"hp,omitempty"`
	Power            *int32 `protobuf:"varint,4,opt,name=power" json:"power,omitempty"`
	StarLevel        *int32 `protobuf:"varint,5,opt,name=star_level" json:"star_level,omitempty"`
	StepLevel        *int32 `protobuf:"varint,6,opt,name=step_level" json:"step_level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_HeroInfo) Reset()         { *m = Game_HeroInfo{} }
func (m *Game_HeroInfo) String() string { return proto.CompactTextString(m) }
func (*Game_HeroInfo) ProtoMessage()    {}

func (m *Game_HeroInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_HeroInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_HeroInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Game_HeroInfo) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Game_HeroInfo) GetStarLevel() int32 {
	if m != nil && m.StarLevel != nil {
		return *m.StarLevel
	}
	return 0
}

func (m *Game_HeroInfo) GetStepLevel() int32 {
	if m != nil && m.StepLevel != nil {
		return *m.StepLevel
	}
	return 0
}

type Game_Attribute struct {
	Key              *int32 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Value            *int32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Group            *int32 `protobuf:"varint,3,opt,name=group" json:"group,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Attribute) Reset()         { *m = Game_Attribute{} }
func (m *Game_Attribute) String() string { return proto.CompactTextString(m) }
func (*Game_Attribute) ProtoMessage()    {}

func (m *Game_Attribute) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Game_Attribute) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Game_Attribute) GetGroup() int32 {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return 0
}

type Game_HeroStruct struct {
	HeroId           *int32            `protobuf:"varint,1,opt,name=hero_id" json:"hero_id,omitempty"`
	HeroUid          *int32            `protobuf:"varint,2,opt,name=hero_uid" json:"hero_uid,omitempty"`
	HeroInfo         *Game_HeroInfo    `protobuf:"bytes,3,opt,name=hero_info" json:"hero_info,omitempty"`
	Attribute        []*Game_Attribute `protobuf:"bytes,4,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_HeroStruct) Reset()         { *m = Game_HeroStruct{} }
func (m *Game_HeroStruct) String() string { return proto.CompactTextString(m) }
func (*Game_HeroStruct) ProtoMessage()    {}

func (m *Game_HeroStruct) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

func (m *Game_HeroStruct) GetHeroUid() int32 {
	if m != nil && m.HeroUid != nil {
		return *m.HeroUid
	}
	return 0
}

func (m *Game_HeroStruct) GetHeroInfo() *Game_HeroInfo {
	if m != nil {
		return m.HeroInfo
	}
	return nil
}

func (m *Game_HeroStruct) GetAttribute() []*Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Game_PropStruct struct {
	PropId           *int32 `protobuf:"varint,1,opt,name=prop_id" json:"prop_id,omitempty"`
	PropUid          *int32 `protobuf:"varint,2,opt,name=prop_uid" json:"prop_uid,omitempty"`
	PropCount        *int32 `protobuf:"varint,3,opt,name=prop_count" json:"prop_count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_PropStruct) Reset()         { *m = Game_PropStruct{} }
func (m *Game_PropStruct) String() string { return proto.CompactTextString(m) }
func (*Game_PropStruct) ProtoMessage()    {}

func (m *Game_PropStruct) GetPropId() int32 {
	if m != nil && m.PropId != nil {
		return *m.PropId
	}
	return 0
}

func (m *Game_PropStruct) GetPropUid() int32 {
	if m != nil && m.PropUid != nil {
		return *m.PropUid
	}
	return 0
}

func (m *Game_PropStruct) GetPropCount() int32 {
	if m != nil && m.PropCount != nil {
		return *m.PropCount
	}
	return 0
}

type Game_FormationStruct struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	HeroUid          *int32 `protobuf:"varint,2,opt,name=hero_uid" json:"hero_uid,omitempty"`
	Pos              *int32 `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_FormationStruct) Reset()         { *m = Game_FormationStruct{} }
func (m *Game_FormationStruct) String() string { return proto.CompactTextString(m) }
func (*Game_FormationStruct) ProtoMessage()    {}

func (m *Game_FormationStruct) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_FormationStruct) GetHeroUid() int32 {
	if m != nil && m.HeroUid != nil {
		return *m.HeroUid
	}
	return 0
}

func (m *Game_FormationStruct) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type Game_EquipInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uid              *int32 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	EquipLevel       *int32 `protobuf:"varint,3,opt,name=equip_level" json:"equip_level,omitempty"`
	StrengthenCount  *int32 `protobuf:"varint,4,opt,name=strengthen_count" json:"strengthen_count,omitempty"`
	RefineCount      *int32 `protobuf:"varint,5,opt,name=refine_count" json:"refine_count,omitempty"`
	Pos              *int32 `protobuf:"varint,6,opt,name=pos" json:"pos,omitempty"`
	Quality          *int32 `protobuf:"varint,7,opt,name=quality" json:"quality,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_EquipInfo) Reset()         { *m = Game_EquipInfo{} }
func (m *Game_EquipInfo) String() string { return proto.CompactTextString(m) }
func (*Game_EquipInfo) ProtoMessage()    {}

func (m *Game_EquipInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_EquipInfo) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Game_EquipInfo) GetEquipLevel() int32 {
	if m != nil && m.EquipLevel != nil {
		return *m.EquipLevel
	}
	return 0
}

func (m *Game_EquipInfo) GetStrengthenCount() int32 {
	if m != nil && m.StrengthenCount != nil {
		return *m.StrengthenCount
	}
	return 0
}

func (m *Game_EquipInfo) GetRefineCount() int32 {
	if m != nil && m.RefineCount != nil {
		return *m.RefineCount
	}
	return 0
}

func (m *Game_EquipInfo) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *Game_EquipInfo) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

type Game_EquipStruct struct {
	EquipInfo        *Game_EquipInfo   `protobuf:"bytes,1,opt,name=equip_info" json:"equip_info,omitempty"`
	Attribute        []*Game_Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Game_EquipStruct) Reset()         { *m = Game_EquipStruct{} }
func (m *Game_EquipStruct) String() string { return proto.CompactTextString(m) }
func (*Game_EquipStruct) ProtoMessage()    {}

func (m *Game_EquipStruct) GetEquipInfo() *Game_EquipInfo {
	if m != nil {
		return m.EquipInfo
	}
	return nil
}

func (m *Game_EquipStruct) GetAttribute() []*Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Game_StageBaseDrop struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Id               *int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Count            *int32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_StageBaseDrop) Reset()         { *m = Game_StageBaseDrop{} }
func (m *Game_StageBaseDrop) String() string { return proto.CompactTextString(m) }
func (*Game_StageBaseDrop) ProtoMessage()    {}

func (m *Game_StageBaseDrop) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_StageBaseDrop) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_StageBaseDrop) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type Game_StageBossDrop struct {
	Conditions       []int32 `protobuf:"varint,1,rep,name=conditions" json:"conditions,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_StageBossDrop) Reset()         { *m = Game_StageBossDrop{} }
func (m *Game_StageBossDrop) String() string { return proto.CompactTextString(m) }
func (*Game_StageBossDrop) ProtoMessage()    {}

func (m *Game_StageBossDrop) GetConditions() []int32 {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type Game_Stage struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	State            *int32 `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	StageId          *int32 `protobuf:"varint,3,opt,name=stage_id" json:"stage_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Stage) Reset()         { *m = Game_Stage{} }
func (m *Game_Stage) String() string { return proto.CompactTextString(m) }
func (*Game_Stage) ProtoMessage()    {}

func (m *Game_Stage) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Stage) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *Game_Stage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

// pid = 1001	客户端发送注册角色信息
type Game_RegisterRole struct {
	PlayerId         *int32  `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	Nick             *string `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	HeroId           *int32  `protobuf:"varint,3,opt,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_RegisterRole) Reset()         { *m = Game_RegisterRole{} }
func (m *Game_RegisterRole) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRole) ProtoMessage()    {}

func (m *Game_RegisterRole) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *Game_RegisterRole) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Game_RegisterRole) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

// pid = 1001 服务器返回 角色注册信息
type Game_RegisterRoleResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_RegisterRoleResult) Reset()         { *m = Game_RegisterRoleResult{} }
func (m *Game_RegisterRoleResult) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRoleResult) ProtoMessage()    {}

func (m *Game_RegisterRoleResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// pid = 1002 获取角色信息
type Game_GetRoleInfo struct {
	PlayerId         *int32 `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_GetRoleInfo) Reset()         { *m = Game_GetRoleInfo{} }
func (m *Game_GetRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_GetRoleInfo) ProtoMessage()    {}

func (m *Game_GetRoleInfo) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// pid = 1002 角色返回
type Game_RoleInfoResult struct {
	IsCreate         *bool                   `protobuf:"varint,1,opt,name=is_create" json:"is_create,omitempty"`
	PlayerInfo       *Game_PlayerInfo        `protobuf:"bytes,2,opt,name=player_info" json:"player_info,omitempty"`
	FormationStruct  []*Game_FormationStruct `protobuf:"bytes,3,rep,name=formation_struct" json:"formation_struct,omitempty"`
	HeroStruct       []*Game_HeroStruct      `protobuf:"bytes,4,rep,name=hero_struct" json:"hero_struct,omitempty"`
	PropStruct       []*Game_PropStruct      `protobuf:"bytes,5,rep,name=prop_struct" json:"prop_struct,omitempty"`
	EquipStruct      []*Game_EquipStruct     `protobuf:"bytes,6,rep,name=equip_struct" json:"equip_struct,omitempty"`
	CopyLevels       []*Game_Stage           `protobuf:"bytes,7,rep,name=copy_levels" json:"copy_levels,omitempty"`
	HangupLevels     []*Game_Stage           `protobuf:"bytes,8,rep,name=hangup_levels" json:"hangup_levels,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Game_RoleInfoResult) Reset()         { *m = Game_RoleInfoResult{} }
func (m *Game_RoleInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_RoleInfoResult) ProtoMessage()    {}

func (m *Game_RoleInfoResult) GetIsCreate() bool {
	if m != nil && m.IsCreate != nil {
		return *m.IsCreate
	}
	return false
}

func (m *Game_RoleInfoResult) GetPlayerInfo() *Game_PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *Game_RoleInfoResult) GetFormationStruct() []*Game_FormationStruct {
	if m != nil {
		return m.FormationStruct
	}
	return nil
}

func (m *Game_RoleInfoResult) GetHeroStruct() []*Game_HeroStruct {
	if m != nil {
		return m.HeroStruct
	}
	return nil
}

func (m *Game_RoleInfoResult) GetPropStruct() []*Game_PropStruct {
	if m != nil {
		return m.PropStruct
	}
	return nil
}

func (m *Game_RoleInfoResult) GetEquipStruct() []*Game_EquipStruct {
	if m != nil {
		return m.EquipStruct
	}
	return nil
}

func (m *Game_RoleInfoResult) GetCopyLevels() []*Game_Stage {
	if m != nil {
		return m.CopyLevels
	}
	return nil
}

func (m *Game_RoleInfoResult) GetHangupLevels() []*Game_Stage {
	if m != nil {
		return m.HangupLevels
	}
	return nil
}

// pid = 1003 关卡挑战
type Game_WarMapStage struct {
	StageId          *int32 `protobuf:"varint,1,opt,name=stage_id" json:"stage_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_WarMapStage) Reset()         { *m = Game_WarMapStage{} }
func (m *Game_WarMapStage) String() string { return proto.CompactTextString(m) }
func (*Game_WarMapStage) ProtoMessage()    {}

func (m *Game_WarMapStage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

// pid = 1003 战斗是否允许 阵容(后期添加) 返回
type Game_MapStageResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_MapStageResult) Reset()         { *m = Game_MapStageResult{} }
func (m *Game_MapStageResult) String() string { return proto.CompactTextString(m) }
func (*Game_MapStageResult) ProtoMessage()    {}

func (m *Game_MapStageResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type Game_Reward struct {
	PlayerExp        *int32              `protobuf:"varint,2,opt,name=player_exp" json:"player_exp,omitempty"`
	PlayerGold       *int32              `protobuf:"varint,3,opt,name=player_gold" json:"player_gold,omitempty"`
	HeroExp          *int32              `protobuf:"varint,4,opt,name=hero_exp" json:"hero_exp,omitempty"`
	Equips           []*Game_EquipStruct `protobuf:"bytes,5,rep,name=equips" json:"equips,omitempty"`
	Props            []*Game_PropStruct  `protobuf:"bytes,6,rep,name=props" json:"props,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_Reward) Reset()         { *m = Game_Reward{} }
func (m *Game_Reward) String() string { return proto.CompactTextString(m) }
func (*Game_Reward) ProtoMessage()    {}

func (m *Game_Reward) GetPlayerExp() int32 {
	if m != nil && m.PlayerExp != nil {
		return *m.PlayerExp
	}
	return 0
}

func (m *Game_Reward) GetPlayerGold() int32 {
	if m != nil && m.PlayerGold != nil {
		return *m.PlayerGold
	}
	return 0
}

func (m *Game_Reward) GetHeroExp() int32 {
	if m != nil && m.HeroExp != nil {
		return *m.HeroExp
	}
	return 0
}

func (m *Game_Reward) GetEquips() []*Game_EquipStruct {
	if m != nil {
		return m.Equips
	}
	return nil
}

func (m *Game_Reward) GetProps() []*Game_PropStruct {
	if m != nil {
		return m.Props
	}
	return nil
}

// pid = 1004 战斗结果客户的通知服务器
type Game_WarMapNoteServer struct {
	Stage            *Game_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_WarMapNoteServer) Reset()         { *m = Game_WarMapNoteServer{} }
func (m *Game_WarMapNoteServer) String() string { return proto.CompactTextString(m) }
func (*Game_WarMapNoteServer) ProtoMessage()    {}

func (m *Game_WarMapNoteServer) GetStage() *Game_Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

// pid = 1004 战斗结果客户的通知服务器 result
type Game_WarMapNoteServerResult struct {
	Reward           *Game_Reward `protobuf:"bytes,1,opt,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_WarMapNoteServerResult) Reset()         { *m = Game_WarMapNoteServerResult{} }
func (m *Game_WarMapNoteServerResult) String() string { return proto.CompactTextString(m) }
func (*Game_WarMapNoteServerResult) ProtoMessage()    {}

func (m *Game_WarMapNoteServerResult) GetReward() *Game_Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

// pid = 1005 扫荡
type Game_SweepMapStage struct {
	StageId          *int32 `protobuf:"varint,1,opt,name=stage_id" json:"stage_id,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_SweepMapStage) Reset()         { *m = Game_SweepMapStage{} }
func (m *Game_SweepMapStage) String() string { return proto.CompactTextString(m) }
func (*Game_SweepMapStage) ProtoMessage()    {}

func (m *Game_SweepMapStage) GetStageId() int32 {
	if m != nil && m.StageId != nil {
		return *m.StageId
	}
	return 0
}

func (m *Game_SweepMapStage) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// pid = 1005 扫荡 result
type Game_SweepMapStageResult struct {
	Result           *int32         `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Reward           []*Game_Reward `protobuf:"bytes,2,rep,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Game_SweepMapStageResult) Reset()         { *m = Game_SweepMapStageResult{} }
func (m *Game_SweepMapStageResult) String() string { return proto.CompactTextString(m) }
func (*Game_SweepMapStageResult) ProtoMessage()    {}

func (m *Game_SweepMapStageResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Game_SweepMapStageResult) GetReward() []*Game_Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

// pid = 1006 服务器主动通知客户端 背包中道具变化(such as:掉落时候 )
type Game_Notice2CProp struct {
	Type             *int32             `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Prop             []*Game_PropStruct `protobuf:"bytes,2,rep,name=prop" json:"prop,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_Notice2CProp) Reset()         { *m = Game_Notice2CProp{} }
func (m *Game_Notice2CProp) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CProp) ProtoMessage()    {}

func (m *Game_Notice2CProp) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Notice2CProp) GetProp() []*Game_PropStruct {
	if m != nil {
		return m.Prop
	}
	return nil
}

// pid = 1008 服务器主动背包中装备变化通知客户端(such as:掉落时候 )1006类似
type Game_Notice2CEquip struct {
	Type             *int32              `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Equip            []*Game_EquipStruct `protobuf:"bytes,2,rep,name=equip" json:"equip,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_Notice2CEquip) Reset()         { *m = Game_Notice2CEquip{} }
func (m *Game_Notice2CEquip) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CEquip) ProtoMessage()    {}

func (m *Game_Notice2CEquip) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Notice2CEquip) GetEquip() []*Game_EquipStruct {
	if m != nil {
		return m.Equip
	}
	return nil
}

// pid = 1009 玩家分解装备
type Game_EquipOperation struct {
	Uid              []int32 `protobuf:"varint,1,rep,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_EquipOperation) Reset()         { *m = Game_EquipOperation{} }
func (m *Game_EquipOperation) String() string { return proto.CompactTextString(m) }
func (*Game_EquipOperation) ProtoMessage()    {}

func (m *Game_EquipOperation) GetUid() []int32 {
	if m != nil {
		return m.Uid
	}
	return nil
}

// pid = 1009 玩家操作背包中的装备 返回
type Game_RopOperationResult struct {
	Prop             []*Game_PropStruct `protobuf:"bytes,1,rep,name=prop" json:"prop,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_RopOperationResult) Reset()         { *m = Game_RopOperationResult{} }
func (m *Game_RopOperationResult) String() string { return proto.CompactTextString(m) }
func (*Game_RopOperationResult) ProtoMessage()    {}

func (m *Game_RopOperationResult) GetProp() []*Game_PropStruct {
	if m != nil {
		return m.Prop
	}
	return nil
}

// pid = 1010 服务器通知客户端玩家基础属性变化
type Game_Notice2CRoleInfo struct {
	Level            *int32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp              *int32 `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Power            *int32 `protobuf:"varint,3,opt,name=power" json:"power,omitempty"`
	Hp               *int32 `protobuf:"varint,4,opt,name=hp" json:"hp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CRoleInfo) Reset()         { *m = Game_Notice2CRoleInfo{} }
func (m *Game_Notice2CRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CRoleInfo) ProtoMessage()    {}

func (m *Game_Notice2CRoleInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_Notice2CRoleInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_Notice2CRoleInfo) GetPower() int32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

func (m *Game_Notice2CRoleInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

// pid = 1011 钱变化
type Game_Notice2CMoney struct {
	Gold             *int32 `protobuf:"varint,1,opt,name=gold" json:"gold,omitempty"`
	Diamond          *int32 `protobuf:"varint,2,opt,name=diamond" json:"diamond,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CMoney) Reset()         { *m = Game_Notice2CMoney{} }
func (m *Game_Notice2CMoney) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CMoney) ProtoMessage()    {}

func (m *Game_Notice2CMoney) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_Notice2CMoney) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

// pid = 1012 体力变化
type Game_Notice2CEnergy struct {
	Energy           *int32 `protobuf:"varint,1,opt,name=energy" json:"energy,omitempty"`
	EnergyMax        *int32 `protobuf:"varint,2,opt,name=energy_max" json:"energy_max,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Notice2CEnergy) Reset()         { *m = Game_Notice2CEnergy{} }
func (m *Game_Notice2CEnergy) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CEnergy) ProtoMessage()    {}

func (m *Game_Notice2CEnergy) GetEnergy() int32 {
	if m != nil && m.Energy != nil {
		return *m.Energy
	}
	return 0
}

func (m *Game_Notice2CEnergy) GetEnergyMax() int32 {
	if m != nil && m.EnergyMax != nil {
		return *m.EnergyMax
	}
	return 0
}

// pid = 1013 关卡变化
type Game_Notice2CheckPoint struct {
	LatestCheckpoint *Game_Stage `protobuf:"bytes,1,opt,name=latest_checkpoint" json:"latest_checkpoint,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_Notice2CheckPoint) Reset()         { *m = Game_Notice2CheckPoint{} }
func (m *Game_Notice2CheckPoint) String() string { return proto.CompactTextString(m) }
func (*Game_Notice2CheckPoint) ProtoMessage()    {}

func (m *Game_Notice2CheckPoint) GetLatestCheckpoint() *Game_Stage {
	if m != nil {
		return m.LatestCheckpoint
	}
	return nil
}

// pid = 1014 离线挂机收益
type Game_OffNotice2CGuaji struct {
	PointId          *int32 `protobuf:"varint,1,opt,name=point_id" json:"point_id,omitempty"`
	Gold             *int32 `protobuf:"varint,2,opt,name=gold" json:"gold,omitempty"`
	Exp              *int32 `protobuf:"varint,3,opt,name=exp" json:"exp,omitempty"`
	GuajiTime        *int32 `protobuf:"varint,4,opt,name=guaji_time" json:"guaji_time,omitempty"`
	KillNpcNum       *int32 `protobuf:"varint,5,opt,name=kill_npc_num" json:"kill_npc_num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_OffNotice2CGuaji) Reset()         { *m = Game_OffNotice2CGuaji{} }
func (m *Game_OffNotice2CGuaji) String() string { return proto.CompactTextString(m) }
func (*Game_OffNotice2CGuaji) ProtoMessage()    {}

func (m *Game_OffNotice2CGuaji) GetPointId() int32 {
	if m != nil && m.PointId != nil {
		return *m.PointId
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetGuajiTime() int32 {
	if m != nil && m.GuajiTime != nil {
		return *m.GuajiTime
	}
	return 0
}

func (m *Game_OffNotice2CGuaji) GetKillNpcNum() int32 {
	if m != nil && m.KillNpcNum != nil {
		return *m.KillNpcNum
	}
	return 0
}

// pid = 1015 在线挂机收益
type Game_OnNotice2CGuaji struct {
	GuajiType        *int32              `protobuf:"varint,1,opt,name=guaji_type" json:"guaji_type,omitempty"`
	NpcId            *int32              `protobuf:"varint,2,opt,name=npc_id" json:"npc_id,omitempty"`
	Gold             *int32              `protobuf:"varint,3,opt,name=gold" json:"gold,omitempty"`
	Exp              *int32              `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	Equips           []*Game_EquipStruct `protobuf:"bytes,5,rep,name=equips" json:"equips,omitempty"`
	Props            []*Game_PropStruct  `protobuf:"bytes,6,rep,name=props" json:"props,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_OnNotice2CGuaji) Reset()         { *m = Game_OnNotice2CGuaji{} }
func (m *Game_OnNotice2CGuaji) String() string { return proto.CompactTextString(m) }
func (*Game_OnNotice2CGuaji) ProtoMessage()    {}

func (m *Game_OnNotice2CGuaji) GetGuajiType() int32 {
	if m != nil && m.GuajiType != nil {
		return *m.GuajiType
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetNpcId() int32 {
	if m != nil && m.NpcId != nil {
		return *m.NpcId
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_OnNotice2CGuaji) GetEquips() []*Game_EquipStruct {
	if m != nil {
		return m.Equips
	}
	return nil
}

func (m *Game_OnNotice2CGuaji) GetProps() []*Game_PropStruct {
	if m != nil {
		return m.Props
	}
	return nil
}

type Game_Conditions struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Count            *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	CurCount         *int32 `protobuf:"varint,3,opt,name=cur_count" json:"cur_count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_Conditions) Reset()         { *m = Game_Conditions{} }
func (m *Game_Conditions) String() string { return proto.CompactTextString(m) }
func (*Game_Conditions) ProtoMessage()    {}

func (m *Game_Conditions) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_Conditions) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *Game_Conditions) GetCurCount() int32 {
	if m != nil && m.CurCount != nil {
		return *m.CurCount
	}
	return 0
}

// pid = 1016 C2S 请求挂机信息
type GameGetGuajiInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GameGetGuajiInfo) Reset()         { *m = GameGetGuajiInfo{} }
func (m *GameGetGuajiInfo) String() string { return proto.CompactTextString(m) }
func (*GameGetGuajiInfo) ProtoMessage()    {}

func (m *GameGetGuajiInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// pid = 1016 请求挂机 返回
type Game_GuajiInfoResult struct {
	Conditions       []*Game_Conditions `protobuf:"bytes,1,rep,name=conditions" json:"conditions,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_GuajiInfoResult) Reset()         { *m = Game_GuajiInfoResult{} }
func (m *Game_GuajiInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_GuajiInfoResult) ProtoMessage()    {}

func (m *Game_GuajiInfoResult) GetConditions() []*Game_Conditions {
	if m != nil {
		return m.Conditions
	}
	return nil
}

// pid = 1017 C2S boss 挑战
type Game_ChallengeBoss struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChallengeBoss) Reset()         { *m = Game_ChallengeBoss{} }
func (m *Game_ChallengeBoss) String() string { return proto.CompactTextString(m) }
func (*Game_ChallengeBoss) ProtoMessage()    {}

func (m *Game_ChallengeBoss) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// pid = 1017 挑战 返回
type Game_ChallengeBossResult struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChallengeBossResult) Reset()         { *m = Game_ChallengeBossResult{} }
func (m *Game_ChallengeBossResult) String() string { return proto.CompactTextString(m) }
func (*Game_ChallengeBossResult) ProtoMessage()    {}

// pid = 1018 客户端通知服务器boss挑战结果
type Game_C2SChallenge struct {
	Stage            *Game_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_C2SChallenge) Reset()         { *m = Game_C2SChallenge{} }
func (m *Game_C2SChallenge) String() string { return proto.CompactTextString(m) }
func (*Game_C2SChallenge) ProtoMessage()    {}

func (m *Game_C2SChallenge) GetStage() *Game_Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

// pid = 1018 服务器返回boss 奖励
type Game_C2SChallengeResult struct {
	PropStruct       []*Game_PropStruct  `protobuf:"bytes,1,rep,name=prop_struct" json:"prop_struct,omitempty"`
	EquipStruct      []*Game_EquipStruct `protobuf:"bytes,2,rep,name=equip_struct" json:"equip_struct,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Game_C2SChallengeResult) Reset()         { *m = Game_C2SChallengeResult{} }
func (m *Game_C2SChallengeResult) String() string { return proto.CompactTextString(m) }
func (*Game_C2SChallengeResult) ProtoMessage()    {}

func (m *Game_C2SChallengeResult) GetPropStruct() []*Game_PropStruct {
	if m != nil {
		return m.PropStruct
	}
	return nil
}

func (m *Game_C2SChallengeResult) GetEquipStruct() []*Game_EquipStruct {
	if m != nil {
		return m.EquipStruct
	}
	return nil
}

// pid 1019 客户端通知服务器退出
type Game_LoginOut struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_LoginOut) Reset()         { *m = Game_LoginOut{} }
func (m *Game_LoginOut) String() string { return proto.CompactTextString(m) }
func (*Game_LoginOut) ProtoMessage()    {}

// pid = 1020 C2S 切换关卡
type Game_ChangeGuajiInfo struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChangeGuajiInfo) Reset()         { *m = Game_ChangeGuajiInfo{} }
func (m *Game_ChangeGuajiInfo) String() string { return proto.CompactTextString(m) }
func (*Game_ChangeGuajiInfo) ProtoMessage()    {}

func (m *Game_ChangeGuajiInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// pid = 1020 C2S 切换关卡 result
type Game_ChangeGuajiInfoResult struct {
	IsOk             *bool  `protobuf:"varint,1,opt,name=is_ok" json:"is_ok,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_ChangeGuajiInfoResult) Reset()         { *m = Game_ChangeGuajiInfoResult{} }
func (m *Game_ChangeGuajiInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_ChangeGuajiInfoResult) ProtoMessage()    {}

func (m *Game_ChangeGuajiInfoResult) GetIsOk() bool {
	if m != nil && m.IsOk != nil {
		return *m.IsOk
	}
	return false
}

// pid = 1021 快速战斗
type Game_FastWar struct {
	Stage            *Game_Stage `protobuf:"bytes,1,opt,name=stage" json:"stage,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Game_FastWar) Reset()         { *m = Game_FastWar{} }
func (m *Game_FastWar) String() string { return proto.CompactTextString(m) }
func (*Game_FastWar) ProtoMessage()    {}

func (m *Game_FastWar) GetStage() *Game_Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

// pid = 1021 快速战斗 result
type Game_FastWarResult struct {
	Reward           *Game_Reward `protobuf:"bytes,1,opt,name=reward" json:"reward,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Game_FastWarResult) Reset()         { *m = Game_FastWarResult{} }
func (m *Game_FastWarResult) String() string { return proto.CompactTextString(m) }
func (*Game_FastWarResult) ProtoMessage()    {}

func (m *Game_FastWarResult) GetReward() *Game_Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}
