// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	S2SSystem
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type S2SSystem struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SSystem) Reset()         { *m = S2SSystem{} }
func (m *S2SSystem) String() string { return proto.CompactTextString(m) }
func (*S2SSystem) ProtoMessage()    {}

type S2SSystem_GetType struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SSystem_GetType) Reset()         { *m = S2SSystem_GetType{} }
func (m *S2SSystem_GetType) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_GetType) ProtoMessage()    {}

func (m *S2SSystem_GetType) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type S2SSystem_LoginInfo struct {
	Type             *int32  `protobuf:"varint,1,opt,name=type,def=1" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Passworld        *string `protobuf:"bytes,3,opt,name=passworld" json:"passworld,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SSystem_LoginInfo) Reset()         { *m = S2SSystem_LoginInfo{} }
func (m *S2SSystem_LoginInfo) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_LoginInfo) ProtoMessage()    {}

const Default_S2SSystem_LoginInfo_Type int32 = 1

func (m *S2SSystem_LoginInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_S2SSystem_LoginInfo_Type
}

func (m *S2SSystem_LoginInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *S2SSystem_LoginInfo) GetPassworld() string {
	if m != nil && m.Passworld != nil {
		return *m.Passworld
	}
	return ""
}

type S2SSystem_RegisterInfo struct {
	Type             *int32  `protobuf:"varint,1,opt,name=type,def=2" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age              *int32  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
	Passworld        *string `protobuf:"bytes,4,opt,name=passworld" json:"passworld,omitempty"`
	Sex              *int32  `protobuf:"varint,5,opt,name=sex" json:"sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SSystem_RegisterInfo) Reset()         { *m = S2SSystem_RegisterInfo{} }
func (m *S2SSystem_RegisterInfo) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_RegisterInfo) ProtoMessage()    {}

const Default_S2SSystem_RegisterInfo_Type int32 = 2

func (m *S2SSystem_RegisterInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_S2SSystem_RegisterInfo_Type
}

func (m *S2SSystem_RegisterInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *S2SSystem_RegisterInfo) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *S2SSystem_RegisterInfo) GetPassworld() string {
	if m != nil && m.Passworld != nil {
		return *m.Passworld
	}
	return ""
}

func (m *S2SSystem_RegisterInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type S2SSystem_Request struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type,def=3" json:"type,omitempty"`
	Result           *int32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SSystem_Request) Reset()         { *m = S2SSystem_Request{} }
func (m *S2SSystem_Request) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_Request) ProtoMessage()    {}

const Default_S2SSystem_Request_Type int32 = 3

func (m *S2SSystem_Request) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_S2SSystem_Request_Type
}

func (m *S2SSystem_Request) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type S2SSystem_ResultChatMsg struct {
	Type             []int32  `protobuf:"varint,1,rep,name=type" json:"type,omitempty"`
	Playername       []string `protobuf:"bytes,2,rep,name=playername" json:"playername,omitempty"`
	Msg              []string `protobuf:"bytes,3,rep,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *S2SSystem_ResultChatMsg) Reset()         { *m = S2SSystem_ResultChatMsg{} }
func (m *S2SSystem_ResultChatMsg) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_ResultChatMsg) ProtoMessage()    {}

func (m *S2SSystem_ResultChatMsg) GetType() []int32 {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *S2SSystem_ResultChatMsg) GetPlayername() []string {
	if m != nil {
		return m.Playername
	}
	return nil
}

func (m *S2SSystem_ResultChatMsg) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

type S2SSystem_ResultInfo struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type,def=5" json:"type,omitempty"`
	Result           *int32 `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SSystem_ResultInfo) Reset()         { *m = S2SSystem_ResultInfo{} }
func (m *S2SSystem_ResultInfo) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_ResultInfo) ProtoMessage()    {}

const Default_S2SSystem_ResultInfo_Type int32 = 5

func (m *S2SSystem_ResultInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_S2SSystem_ResultInfo_Type
}

func (m *S2SSystem_ResultInfo) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}
