// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	S2SSystem
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type S2SSystem struct {
	Mylogininfo      *S2SSystem_LoginInfo    `protobuf:"bytes,1,opt,name=mylogininfo" json:"mylogininfo,omitempty"`
	Myregisterinfo   *S2SSystem_RegisterInfo `protobuf:"bytes,2,opt,name=myregisterinfo" json:"myregisterinfo,omitempty"`
	Mychatmsg        *S2SSystem_ChatMsg      `protobuf:"bytes,3,opt,name=mychatmsg" json:"mychatmsg,omitempty"`
	Resultinfo       *S2SSystem_ResultInfo   `protobuf:"bytes,4,opt,name=resultinfo" json:"resultinfo,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *S2SSystem) Reset()         { *m = S2SSystem{} }
func (m *S2SSystem) String() string { return proto.CompactTextString(m) }
func (*S2SSystem) ProtoMessage()    {}

func (m *S2SSystem) GetMylogininfo() *S2SSystem_LoginInfo {
	if m != nil {
		return m.Mylogininfo
	}
	return nil
}

func (m *S2SSystem) GetMyregisterinfo() *S2SSystem_RegisterInfo {
	if m != nil {
		return m.Myregisterinfo
	}
	return nil
}

func (m *S2SSystem) GetMychatmsg() *S2SSystem_ChatMsg {
	if m != nil {
		return m.Mychatmsg
	}
	return nil
}

func (m *S2SSystem) GetResultinfo() *S2SSystem_ResultInfo {
	if m != nil {
		return m.Resultinfo
	}
	return nil
}

type S2SSystem_LoginInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Passworld        *string `protobuf:"bytes,2,req,name=passworld" json:"passworld,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SSystem_LoginInfo) Reset()         { *m = S2SSystem_LoginInfo{} }
func (m *S2SSystem_LoginInfo) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_LoginInfo) ProtoMessage()    {}

func (m *S2SSystem_LoginInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *S2SSystem_LoginInfo) GetPassworld() string {
	if m != nil && m.Passworld != nil {
		return *m.Passworld
	}
	return ""
}

type S2SSystem_RegisterInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Passworld        *string `protobuf:"bytes,2,req,name=passworld" json:"passworld,omitempty"`
	Age              *int32  `protobuf:"varint,3,req,name=age" json:"age,omitempty"`
	Sex              *int32  `protobuf:"varint,4,req,name=sex" json:"sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SSystem_RegisterInfo) Reset()         { *m = S2SSystem_RegisterInfo{} }
func (m *S2SSystem_RegisterInfo) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_RegisterInfo) ProtoMessage()    {}

func (m *S2SSystem_RegisterInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *S2SSystem_RegisterInfo) GetPassworld() string {
	if m != nil && m.Passworld != nil {
		return *m.Passworld
	}
	return ""
}

func (m *S2SSystem_RegisterInfo) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *S2SSystem_RegisterInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type S2SSystem_ChatMsg struct {
	Playername       *string `protobuf:"bytes,1,req,name=playername" json:"playername,omitempty"`
	Msg              *string `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2SSystem_ChatMsg) Reset()         { *m = S2SSystem_ChatMsg{} }
func (m *S2SSystem_ChatMsg) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_ChatMsg) ProtoMessage()    {}

func (m *S2SSystem_ChatMsg) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

func (m *S2SSystem_ChatMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type S2SSystem_ResultInfo struct {
	Result           *int32 `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *S2SSystem_ResultInfo) Reset()         { *m = S2SSystem_ResultInfo{} }
func (m *S2SSystem_ResultInfo) String() string { return proto.CompactTextString(m) }
func (*S2SSystem_ResultInfo) ProtoMessage()    {}

func (m *S2SSystem_ResultInfo) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}
